### PR TITLE
nacos config bug fix

### LINKED ISSUE #277: Nacos Config 0.2.2 支持 共享和扩展配置 有问题
在使用 Spring Cloud Alibaba Nacos Config 时，通过：

spring.cloud.nacos.config.shared-data-ids=****.properties
或者
spring.cloud.nacos.config.ext-config[0].data-id=****.properties

配置，客户端抛出异常。

### PR DESCRIPTION
**Pull request by pbting**
fix #277

### CODE REVIEW

File: spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java [hunk 1]
```diff
@@ -186,12 +185,17 @@ private void loadNacosDataIfPresent(final CompositePropertySource composite,
...
 				if (sharedDataIdArry[i].indexOf(fileExtension) > 0) {
+					isLegal = true;
 					break;
 				}
 			}
-			stringBuilder.append(sharedDataIdArry[i] + ",");
+			// add tips
+			if (!isLegal) {
+				stringBuilder.append(sharedDataIdArry[i] + ",");
+			}
```
Comment (flystar32) [inline spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java]: in line 209，checkDataIdIsRefreshbable has typo

**Comment by fangjian0423** [comment]
LGTM
